### ISSUE TITLE
Rust / Cargo    1: failed to spawn command "cargo": Is Cargo installed?   

### ISSUE THREAD

**Issue by marvin-hansen** [phylum-dev/phylum-analyze-pr-action#29]
## Describe the bug

CI fails consistently with the following error 

```
Run phylum-dev/phylum-analyze-pr-action@v2
  with:
    phylum_token: ***
    cmd: phylum-ci --all-deps
    github_token: ***
```
...

```
╭────────────────────────────── Subprocess Error ──────────────────────────────╮
│ COMMAND: /usr/local/bin/phylum parse Cargo.toml                              │
│ RETURN CODE: 1                                                               │
│ ╭───────────────────────────────── STDERR ─────────────────────────────────╮ │
│ │ Generating lockfile for manifest "Cargo.toml" using Cargo…               │ │
│ │ ❗ Error: could not parse lockfile: Cargo.toml                           │ │
│ │                                                                          │ │
│ │ Caused by:                                                               │ │
│ │     0: Lockfile generation failed! For details, see:                     │ │
│ │ https://docs.phylum.io/docs/lockfile_generation                          │ │
│ │     1: failed to spawn command "cargo": Is Cargo installed?              │ │
│ │     [2](https://github.com/deepcausality-rs/deep_causality/actions/runs/6160768107/job/16718473682#step:4:2): No such file or directory (os error 2)                            │ │
│ ╰──────────────────────────────────────────────────────────────────────────╯ │
╰──────────────────────────────────────────────────────────────────────────────╯
Provided lockfile failed to parse as a known lockfile type: Cargo.toml          

No valid lockfiles were detected. Consider specifying at least one with `--lockfile`.
```

## To Reproduce

1. Go to https://github.com/phylum-dev/phylum-analyze-pr-action

2. Follow instructions
a) Add API key
b) Add GH action (copy & paste)
c) Commit to repo

3. Trigger CI & See error

## Expected behavior

This should run.

For reference, phylum CLI analyzes a local clone of the repo just fine. You can try it.

## Additional context

GH action
https://github.com/deepcausality-rs/deep_causality/blob/main/.github/workflows/run_dep_sec_scan.yml

Failed run
https://github.com/deepcausality-rs/deep_causality/actions/runs/6160768107/job/16718473682

Repo
https://github.com/deepcausality-rs/deep_causality

.phylum_project
https://github.com/deepcausality-rs/deep_causality/blob/main/.phylum_project

**Comment by marvin-hansen** [comment]
Verbose error log from manually specified lockfile. 

https://github.com/deepcausality-rs/deep_causality/actions/runs/6160935691/job/16718998374

**Comment by maxrake** [comment]
Thank you for trying Phylum and providing feedback!

In this case, the failure is a known limitation of the action. The docker image used for this action - `docker://ghcr.io/phylum-dev/phylum-ci:latest` - does not yet include the [required tools for lockfile generation](https://docs.phylum.io/docs/lockfile_generation)...`cargo` in this case.

Updates are planned to allow for manifest support and lockfile generation completely within the docker image and this action...it just hasn't happened yet. In the mean time, there are [possible alternatives](https://docs.phylum.io/docs/github_actions#alternatives) to consider. Basically, if `cargo` is installed in the environment, then operation should proceed as expected and like when using the CLI locally.

**Comment by marvin-hansen** [comment]
@maxrake I've patched your docker image to add cargo support.

Please review PR: https://github.com/phylum-dev/phylum-ci/pull/310

**Comment by maxrake** [comment]
Closing this issue now that initial manifest support (to include Rust/Cargo) is available in this action, with the [latest release of `phylum-ci`](https://github.com/phylum-dev/phylum-ci/releases/tag/v0.36.0).
